# Generated by Django 5.1.7 on 2025-03-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='citi',
            new_name='city',
        ),
    ]
